version: '3.8'
services:
  backend:
    build:
      context: . # Context is the project root for the backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - frontend
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: . # Context is the client directory for the frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
